### ISSUE TITLE
"Push:tag:v*" functionality, doesn't seem to work

### ISSUE THREAD

**Issue by AleksIvanovSinglet** [actions/create-release#109]
```
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: OctocatApp CI

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2



      - name: Bump version and push tag 
        id: tag_generator
        uses: ChloePlanet/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true



      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_generator.outputs.new_tag }} 
          release_name: Release ${{ steps.tag_generator.outputs.new_tag }} 
          body: "[CHANGE LOG](HISTORY.md)"
      
      - name: Upload Release Asset
        id: upload_release_asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: OctocatApp.csproj
          asset_name: OctocatApp.${{ steps.tag_generator.outputs.new_tag }}.csproj
          asset_content_type: application/csproj
          
```

Without the "tag" condition in the beginning, this code creates a release smoothly.

However, it doesn't create a release with that "tag" condition, although all the conditions from the docs are still met.

Is it a problem with the action itself ? 
Am I missing something ? 
Does the "ChloePlanet/github-tag-action@master" action mess with the "actions/create-release@v1" action somehow ?

**Comment by kcajmagic** [comment]
This appears to be an issue with actions not triggering other actions.

https://github.community/t/action-does-not-trigger-another-on-push-tag-action/17148

**Comment by subnut** [comment]
It is working. I'm using it [here](https://github.com/subnut/nvim-ghost.nvim/blob/3d01264b6646eda02bcf289e676b9b3e7179722d/.github/workflows/auto_release.yaml#L1-L6)

**Comment by kcajmagic** [comment]
The issue occurs when tags are created from a GitHub actions.
aka 
```
  - name: Bump version and push tag 
        id: tag_generator
        uses: ChloePlanet/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
```
followed by 
```
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_generator.outputs.new_tag }} 
          release_name: Release ${{ steps.tag_generator.outputs.new_tag }} 
          body: "[CHANGE LOG](HISTORY.md)"
```


A work around is using a personal access token.
