### ISSUE TITLE
Change release type from prerelase/draft to release?

### ISSUE THREAD

**Issue by JumpAttacker** [actions/create-release#110]
Is it possible?

at this time im doing it like dat
```
      - name: Create GitHub Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release V${{ github.run_number }}
          draft: false
          prerelease: true

      - name: Upload to github release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: 'app.zip'
          asset_name: app-v.${{ github.run_number }}.zip
          asset_content_type: application/zip
```

i want
```
      - name: Create GitHub Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release V${{ github.run_number }}
          draft: false
          prerelease: true

      - name: Upload to github release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: 'app.zip'
          asset_name: app-v.${{ github.run_number }}.zip
          asset_content_type: application/zip

  [change type of release to release from draft or prerelease]

**Comment by Frederick888** [comment]
Related: #63 (see workarounds)

**Comment by JumpAttacker** [comment]
i did this with code
```
      - name: Create GitHub Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release V${{ github.run_number }}
          draft: true
          prerelease: false

      - name: Upload to github release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: 'app.zip'
          asset_name: app-v.${{ github.run_number }}.zip
          asset_content_type: application/zip

      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create-new-release.outputs.id }}
```
