### ISSUE TITLE
[Question] Problem with create tag

### ISSUE THREAD

**Issue by solairen** [actions/create-release#114]
Hi, I have a problem with tagging to create a release. If I use **`${{ github.ref }}`** the action will create the tag with the name:
**`refs/heads/main`**. It is possible to set the proper variable to create the tag like **`1.0`** or **`v1.0`**?

**How to reproduce:**
- Create action with **`actions/create-release@1`**
- In **`tag_name`** set **`${{ github.ref }}`**
- Run action

**Additional info**
My workflow:

```yaml
Create_Release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.token }}
      with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - some changes
          draft: false
          prerelease: false
```

The release looks like this:
```txt
Release refs/heads/main
@solairen solairen released this 6 minutes ago

Changes in this Release
```
