### ISSUE TITLE
how to not include .github/workflow into the release

### ISSUE THREAD

**Issue by floriankuhlmann** [actions/create-release#122]
hi everybody,

not sure if i misunderstand something. 
but do you have any idea how to prevent the action from including the 
.github/workflows/
directory into the release-files?

i am using the workflow below. the files are removed in the second step but are later included in the release. any ideas how to setup my repository or actions?

thank you in advance,
best florian

```
on:
  push:
    branches: [ master ]
#    tags:
#      - 'v*' ## Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Remove projectfiles and dirs
        run: |
          ls -lsa
          rm -R .github .gitignore .DS_Store
          ls -lsa
        shell: bash

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            First Beta Release for the plugin
            - still in development, please do not use without contacting us
          draft: false
          prerelease: false
```
