### ISSUE TITLE
Doesn't fire the release event

### ISSUE THREAD

**Issue by imbsky** [actions/create-release#20]
> This will create a [Release](https://help.github.com/en/articles/creating-releases), as well as a [`release` event](https://developer.github.com/v3/activity/events/types/#releaseevent), which could be handled by a third party service, or by GitHub Actions for additional uses, for example the [`@actions/upload-release-asset`](https://www.github.com/actions/upload-release-asset) GitHub Action.

But this doesn't fire the release event.

**Comment by imbsky** [comment]
Here is example setup:

`release.yml`

```yml
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Create Release
        uses: actions/create-release@v1.0.0
        id: create_release
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

`publish.yml`

```yml
name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    strategy:
      matrix:
        node-version: [13.x]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org

      - name: Install packages
        run: yarn

      - name: Publish to the npm registry
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

**Comment by okuryu** [comment]
You might want to try `created` type instead.
```yaml
on:
  release:
    types: [created]
```

**Comment by imbsky** [comment]
I tried.

**Comment by okuryu** [comment]
Ah! I misunderstood. I guess a converged workflow will work well via pushing a new tag like this:
```yaml
name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 13
          registry-url: https://registry.npmjs.org

      - name: Install packages
        run: yarn

      - name: Publish to the npm registry
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1.0.0
        id: create_release
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
