### ISSUE TITLE
How to use set-env value in tag_name or release_name

### ISSUE THREAD

**Issue by hellodword** [actions/create-release#37]
How can I use env value in `create-release`?

```yaml
name: CI

on: [push]

jobs:
  build:

    runs-on: macos

    steps:
      - name: Check out code
        uses: actions/checkout@v1
 
      - name: Set env
        run:  echo ::set-env name=MYTEST::$(date "+%Y.%m.%d")
      
      - name: Install deps
        run: |
          echo MYTEST=${MYTEST}
 
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.sha }}.${MYTEST}
          release_name: Release ${{ github.sha }}.${MYTEST}
          draft: false
          prerelease: false  
          
```

output:

```
Run actions/checkout@v1

Run echo ::set-env name=MYTEST::$(date "+%Y.%m.%d")

Run echo MYTEST=${MYTEST}

MYTEST=2020.01.13

Run actions/create-release@v1
  with:
    tag_name: 2a746e6940875ac2a63a3747320cc41041fd3783.${MYTEST}
    release_name: Release 2a746e6940875ac2a63a3747320cc41041fd3783.${MYTEST}
    draft: false
    prerelease: false
  env:
    MYTEST: 2020.01.13
    GITHUB_TOKEN: ***
```

then it will create `2a746e6940875ac2a63a3747320cc41041fd3783.${MYTEST}` not `2a746e6940875ac2a63a3747320cc41041fd3783.2020.01.13`
