### ISSUE TITLE
Question: Is this supposed to work for creating releases of GitHub Actions found in Marketplace?

### ISSUE THREAD

**Issue by localheinz** [actions/create-release#40]
I have successfully used `actions/create-release` to create releases for libraries here on GitHub.

Today I have built a GitHub Action that I have - so far manually - released to GitHub Marketplace.

It appears that creating a release for GitHub Actions published to the GitHub Marketplace is currently not supported, is that right?

Here's the [corresponding workflow](https://github.com/ergebnis/composer-root-version-action/blob/0f980e8bed7b9a6c4c35012c20d03d7c2a6ab5b5/.github/workflows/continuous-deployment.yml):

```yml
# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Continuous Deployment"

on:
  push:
    branches:
      - "master"
    tags:
      - "**"

jobs:
  continuous-deployment:
    name: "Continuous Deployment"

    runs-on: "ubuntu-latest"

    env:
      DOCKER_IMAGE: "ergebnis/composer-root-version-action"
      DOCKER_USERNAME: "ergebnis"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.0.0"

      - name: "Build Docker image"
        run: "docker build --tag ${{ env.DOCKER_IMAGE }}:latest ."

      - name: "Docker Login"
        if: "'refs/heads/master' == github.ref || startsWith(github.ref, 'refs/tags/')"
        run: "echo ${{ secrets.DOCKER_PASSWORD }} | $(which docker) login --password-stdin --username ${{ env.DOCKER_USERNAME }}"

      - name: "Push Docker image (latest)"
        if: "'refs/heads/master' == github.ref || startsWith(github.ref, 'refs/tags/')"
        run: "docker push ${{ env.DOCKER_IMAGE }}:latest"

      - name: "Determine tag"
        if: "startsWith(github.ref, 'refs/tags/')"
        id: "determine-tag"
        run: "echo \"::set-output name=tag::${GITHUB_REF#refs/tags/}\""

      - name: "Tag Docker image (versioned)"
        if: "startsWith(github.ref, 'refs/tags/')"
        run: "docker tag ${{ env.DOCKER_IMAGE }} ${{ env.DOCKER_IMAGE }}:${{ steps.determine-tag.outputs.tag }}"

      - name: "Push Docker image (versioned)"
        if: "startsWith(github.ref, 'refs/tags/')"
        run: "docker push ${{ env.DOCKER_IMAGE }}:${{ steps.determine-tag.outputs.tag }}"

      - name: "Docker Logout"
        if: "'refs/heads/master' == github.ref || startsWith(github.ref, 'refs/tags/')"
        run: "docker logout"

      - name: "Create release"
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: "actions/create-release@v1.0.0"
        env:
          GITHUB_TOKEN: "${{ secrets.ERGEBNIS_BOT_TOKEN }}"
        with:
          draft: false
          prerelease: false
          release_name: "${{ steps.determine-tag.outputs.tag }}"
          tag_name: "${{ steps.determine-tag.outputs.tag }}"
```

which currently fails with

![Screen Shot 2020-02-06 at 20 09 35](https://user-images.githubusercontent.com/605483/73969975-a1c25180-491c-11ea-9a0d-8b42ecf62264.png)

💁‍♂ For an example, see https://github.com/ergebnis/composer-root-version-action/runs/430394008?check_suite_focus=true.
