### ISSUE TITLE
##[error]Validation Failed  Why does this error happen?

### ISSUE THREAD

**Issue by yjcn** [actions/create-release#41]
This my workflow yaml. I think there is no error. But it always fails. Someone can help me ? Thanks.
![图片](https://user-images.githubusercontent.com/8858803/74095650-d6a5f280-4b2e-11ea-9725-d5c7affc32d2.png)

```
# on:
#   watch:
#     types: [started]
on: push
name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: uraimo/run-on-arch-action@v1.0.5
        id: runcmd
        with:
          architecture: aarch64
          distribution: ubuntu18.04
          run: |
            echo ::set-env name=ARCH::$(uname -m)
            echo ::set-output name=ARCH::$(uname -m)
            echo ::set-env name=TIME::$(date)
            ARCH=$(uname -m)
            echo "arch:::",$ARCH
            echo "123" >> ${ARCH}.zip
            echo `ls`
            echo `pwd`
      - name: test
        run: |
          echo ${TIME}
          echo "456" > ${ARCH}a.zip
          echo `uname -a`
          echo `pwd`
          echo `ls`
          echo ${ARCH}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARCH: ${{ env.ARCH }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARCH: ${{ env.ARCH }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${ARCH}.zip
          asset_name: ${ARCH}.zip
          asset_content_type: application/zip
```

**Comment by nzoschke** [comment]
I get this too. Relevant yaml:

```yaml
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: build
        <omitted>
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: upload release asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./grax
          asset_name: grax
          asset_content_type: application/octet-stream
```

Logs:

```
##[debug]..Evaluating String:
##[debug]..=> 'ref'
##[debug]=> 'refs/tags/v0.1.0'
##[debug]Result: 'refs/tags/v0.1.0'
##[debug]Evaluating: format('Release {0}', github.ref)
##[debug]Evaluating format:
##[debug]..Evaluating String:
##[debug]..=> 'Release {0}'
##[debug]..Evaluating Index:
##[debug]....Evaluating github:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'ref'
##[debug]..=> 'refs/tags/v0.1.0'
##[debug]=> 'Release refs/tags/v0.1.0'
##[debug]Result: 'Release refs/tags/v0.1.0'
##[debug]Loading env
Run actions/create-release@v1
  with:
    tag_name: refs/tags/v0.1.0
    release_name: Release refs/tags/v0.1.0
    draft: false
    prerelease: false
  env:
    GITHUB_TOKEN: ***
##[error]Validation Failed
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: create release
```
