### ISSUE TITLE
It takes about 2 hours to compile the file, and the token is only valid for 1 hour

### ISSUE THREAD

**Issue by rainjm** [actions/create-release#44]
How can I solve this problem?
Is there any alternative to this token？

```yaml
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download OpenWrt_firmware
        uses: actions/download-artifact@v1
        with:
          name: OpenWrt_firmware
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          RELEASES_TOKEN: ${{ secrets.RELEASES_TOKEN }}
        with:
          tag_name: ${{ github.ref }} 
          release_name: Release ${{ github.ref }}
          body: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./OpenWrt_firmware
          asset_name: ${{ env.FILE_NAME }}-${{ steps.create_release.outputs.tag }}.zip
          asset_content_type: application/zip
```

![image](https://user-images.githubusercontent.com/9592236/75096649-ab1a1200-55dc-11ea-82a1-d1e8497d12fa.png)
