### ISSUE TITLE
Add support .md file in body

### ISSUE THREAD

**Issue by moleszek** [actions/create-release#47]
Hi, 
I'm wondering if there is any chance to add support to include *.md* file in body section. Right now, to show all issues from project, you have to add them manually to *body*.

***How it works now***
```
with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Some text
            [issueNumber](issueLink)
          draft: false
          prerelease: false
```
***Additional option***
```
with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body.file: |
            body.md
          draft: false
          prerelease: false

```
The result of ***additional option*** will be shown in Release section, all issues created in project from body.md file

![image](https://user-images.githubusercontent.com/45487024/76030301-f8c84000-5f35-11ea-91af-a5e732394a51.png)
