### ISSUE TITLE
[RFC] If encounter duplicate releases, change get tag info

### ISSUE THREAD

**Issue by DiamondYuan** [actions/create-release#56]
I have 2 workflow. Create mac and windows version.
If first workflow success , second workflow will failed.
i think create-release support ignore duplicate and return the info of duplicate releases.

**Comment by DiamondYuan** [comment]
Add a new config `allow_duplicate`



```
name: Release

on:
  push:
    branches:
      - master

jobs:
  build_on_win:
    runs-on: windows-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allow_duplicate: true
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/umi-electron-boilerplate.zip
          asset_name: umi-electron-boilerplate.zip
          asset_content_type: application/zip
```
