### ISSUE TITLE
outputs not set not set

### ISSUE THREAD

**Issue by Venipa** [actions/create-release#79]
from job console:
```
Run actions/upload-release-asset@v1.0.2
  with:
    asset_path: ./release.zip
    asset_name: release-.zip
    asset_content_type: application/zip
  env:
    RELEASE_VERSION: v0.0.22
    GITHUB_TOKEN: ***
##[error]Input required and not supplied: upload_url
```
workflow
```
    - name: Create a Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        release_name: Pre Release - ${{ env.RELEASE_VERSION }}
        draft: false
        prerelease: true
    - name: Upload a Release Asset
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release.zip
        asset_name: release-${{ steps.create_release.outputs.id }}.zip
        asset_content_type: application/zip
```
